---
name: Unit Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run test on ${{ matrix.os }} and Dart on branch ${{ matrix.dart-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        dart-version: [latest, dev]

    container:
      image: google/dart:${{ matrix.dart-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: $HOME/.pub-cache
          key: pub-${{ matrix.os }}-${{ matrix.dart-version }}-${{ hashFiles('pubspec.yaml') }}

      - name: Installing dependencies
        run: pub get

      - name: Run tests
        run: pub run test
